server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jzityxf/config/     # 配置git仓库的地址
          search-paths: config-file                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: jzityxf                                        # git仓库的账号
          password: 197871                                    # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
      
management:
  security:
     enabled: false

