server:
  port: 8010
spring:
  application:
    name: feign-consumer-movie-mult
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true